### ISSUE TITLE
React 18 support 

### ISSUE THREAD

**Issue by ibrown-epic-games** [dunglas/react-esi#44]
How does this look for supporting react 18 and server components? I also noticed that trying to install this with React 18 is currently broken as the peer dependency on react 17 does not allow it to install.

<img width="585" alt="image" src="https://github.com/dunglas/react-esi/assets/135380296/8d3d3f82-3cec-4cb5-b385-f5527908b69f">

**Comment by dunglas** [comment]
Hi,

Yes supporting React 18 and server components is definitely a goal, but there is no ETA yet.

As usual, patches are very welcome :)

**Comment by dunglas** [comment]
Closed by #46.
