### ISSUE TITLE
The configuration example link is broken in the README

### ISSUE THREAD

**Issue by BenMorel** [dunglas/react-esi#57]
This link in the README: https://github.com/zeit/next.js/blob/canary/examples/with-react-esi/docker/varnish/default.vcl is broken.

I suppose the configuration example should look like this: https://github.com/symfony/symfony-docs/issues/14640#issuecomment-756681357

Should this example be hardcoded in the README instead?

**Comment by dunglas** [comment]
This PR contains up to date code and examples: https://github.com/dunglas/react-esi/pull/55
