### ISSUE TITLE
cloudflare workers 

### ISSUE THREAD

**Issue by nikitapilgrim** [dunglas/react-esi#8]
This can be used to create an ssr application using cloudflare workers? 
I want React PWA, next.js, cloudflare workers

**Comment by dunglas** [comment]
You indeed use Cloudflare worker as an ESI server (https://new.blog.cloudflare.com/edge-side-includes-with-cloudflare-workers/). However you cannot use the library directly in CFW. Also, I'm working on a new library dedicated designed to run as CFW application (it will be a separate project).

**Comment by nikitapilgrim** [comment]
I look forward to it. CFW This is really a terrific approach. 
I think this is probably the best deal on the market. But there are a lot of difficulties with setting up the deployment
Need to make the web fast.

**Comment by tempo22** [comment]
> You indeed use Cloudflare worker as an ESI server (https://new.blog.cloudflare.com/edge-side-includes-with-cloudflare-workers/). However you cannot use the library directly in CFW. Also, I'm working on a new library dedicated designed to run as CFW application (it will be a separate project).

Hi! Sorry to bump this closed topic but i'm also really interested in running this as a CFW app.
Do you have started that project yet ?

**Comment by dunglas** [comment]
Actually I created a tiny SSR/ESI framework for Cloudflare Worker based on this lib a while ago but never got the time to release it publicly. Unfortunately I don't know when I'll be able to finish and publish this tool.

**Comment by aequasi** [comment]
Will that work for Serverless in general (e.g. ZEIT now)?
